/*
Navicat MySQL Data Transfer

Source Server         : localhot
Source Server Version : 100116
Source Host           : localhost:3306
Source Database       : crm

Target Server Type    : MYSQL
Target Server Version : 100116
File Encoding         : 65001

Date: 2018-08-07 09:16:18
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for county
-- ----------------------------
DROP TABLE IF EXISTS `county`;
CREATE TABLE `county` (
  `id` smallint(5) unsigned NOT NULL,
  `province_id` smallint(5) unsigned NOT NULL,
  `name` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `province_id` (`province_id`),
  CONSTRAINT `county_ibfk_1` FOREIGN KEY (`province_id`) REFERENCES `province` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of county
-- ----------------------------
INSERT INTO `county` VALUES ('1', '1', 'آذرشهر');
INSERT INTO `county` VALUES ('2', '1', 'اسکو');
INSERT INTO `county` VALUES ('3', '1', 'اهر');
INSERT INTO `county` VALUES ('4', '1', 'بستان آباد');
INSERT INTO `county` VALUES ('5', '1', 'بناب');
INSERT INTO `county` VALUES ('6', '1', 'تبریز');
INSERT INTO `county` VALUES ('7', '1', 'جلفا');
INSERT INTO `county` VALUES ('8', '1', 'چاراویماق');
INSERT INTO `county` VALUES ('9', '1', 'خداآفرین');
INSERT INTO `county` VALUES ('10', '1', 'سراب');
INSERT INTO `county` VALUES ('11', '1', 'شبستر');
INSERT INTO `county` VALUES ('12', '1', 'عجب شیر');
INSERT INTO `county` VALUES ('13', '1', 'کلیبر');
INSERT INTO `county` VALUES ('14', '1', 'مراغه');
INSERT INTO `county` VALUES ('15', '1', 'مرند');
INSERT INTO `county` VALUES ('16', '1', 'ملکان');
INSERT INTO `county` VALUES ('17', '1', 'میانه');
INSERT INTO `county` VALUES ('18', '1', 'ورزقان');
INSERT INTO `county` VALUES ('19', '1', 'هریس');
INSERT INTO `county` VALUES ('20', '1', 'هشترود');
INSERT INTO `county` VALUES ('21', '2', 'ارومیه');
INSERT INTO `county` VALUES ('22', '2', 'اشنویه');
INSERT INTO `county` VALUES ('23', '2', 'بوکان');
INSERT INTO `county` VALUES ('24', '2', 'پلدشت');
INSERT INTO `county` VALUES ('25', '2', 'پیرانشهر');
INSERT INTO `county` VALUES ('26', '2', 'تکاب');
INSERT INTO `county` VALUES ('27', '2', 'چالدران');
INSERT INTO `county` VALUES ('28', '2', 'چایپاره');
INSERT INTO `county` VALUES ('29', '2', 'خوی');
INSERT INTO `county` VALUES ('30', '2', 'سردشت');
INSERT INTO `county` VALUES ('31', '2', 'سلماس');
INSERT INTO `county` VALUES ('32', '2', 'شاهین دژ');
INSERT INTO `county` VALUES ('33', '2', 'شوط');
INSERT INTO `county` VALUES ('34', '2', 'ماکو');
INSERT INTO `county` VALUES ('35', '2', 'مهاباد');
INSERT INTO `county` VALUES ('36', '2', 'میاندوآب');
INSERT INTO `county` VALUES ('37', '2', 'نقده');
INSERT INTO `county` VALUES ('38', '3', 'اردبیل');
INSERT INTO `county` VALUES ('39', '3', 'بیله سوار');
INSERT INTO `county` VALUES ('40', '3', 'پارس آباد');
INSERT INTO `county` VALUES ('41', '3', 'خلخال');
INSERT INTO `county` VALUES ('42', '3', 'سرعین');
INSERT INTO `county` VALUES ('43', '3', 'کوثر');
INSERT INTO `county` VALUES ('44', '3', 'گرمی');
INSERT INTO `county` VALUES ('45', '3', 'مشگین شهر');
INSERT INTO `county` VALUES ('46', '3', 'نمین');
INSERT INTO `county` VALUES ('47', '3', 'نیر');
INSERT INTO `county` VALUES ('48', '4', 'آران وبیدگل');
INSERT INTO `county` VALUES ('49', '4', 'اردستان');
INSERT INTO `county` VALUES ('50', '4', 'اصفهان');
INSERT INTO `county` VALUES ('51', '4', 'برخوار');
INSERT INTO `county` VALUES ('52', '4', 'بو یین و میاندشت');
INSERT INTO `county` VALUES ('53', '4', 'تیران وکرون');
INSERT INTO `county` VALUES ('54', '4', 'چادگان');
INSERT INTO `county` VALUES ('55', '4', 'خمینی شهر');
INSERT INTO `county` VALUES ('56', '4', 'خوانسار');
INSERT INTO `county` VALUES ('57', '4', 'خور و بیابانک');
INSERT INTO `county` VALUES ('58', '4', 'دهاقان');
INSERT INTO `county` VALUES ('59', '4', 'سمیرم');
INSERT INTO `county` VALUES ('60', '4', 'شاهین شهرومیمه');
INSERT INTO `county` VALUES ('61', '4', 'شهرضا');
INSERT INTO `county` VALUES ('62', '4', 'فریدن');
INSERT INTO `county` VALUES ('63', '4', 'فریدونشهر');
INSERT INTO `county` VALUES ('64', '4', 'فلاورجان');
INSERT INTO `county` VALUES ('65', '4', 'کاشان');
INSERT INTO `county` VALUES ('66', '4', 'گلپایگان');
INSERT INTO `county` VALUES ('67', '4', 'لنجان');
INSERT INTO `county` VALUES ('68', '4', 'مبارکه');
INSERT INTO `county` VALUES ('69', '4', 'نایین');
INSERT INTO `county` VALUES ('70', '4', 'نجف آباد');
INSERT INTO `county` VALUES ('71', '4', 'نطنز');
INSERT INTO `county` VALUES ('72', '5', 'اشتهارد');
INSERT INTO `county` VALUES ('73', '5', 'ساوجبلاغ');
INSERT INTO `county` VALUES ('74', '5', 'طالقان');
INSERT INTO `county` VALUES ('75', '5', 'فردیس');
INSERT INTO `county` VALUES ('76', '5', 'کرج');
INSERT INTO `county` VALUES ('77', '5', 'نظرآباد');
INSERT INTO `county` VALUES ('78', '6', 'آبدانان');
INSERT INTO `county` VALUES ('79', '6', 'ایلام');
INSERT INTO `county` VALUES ('80', '6', 'ایوان');
INSERT INTO `county` VALUES ('81', '6', 'بدره');
INSERT INTO `county` VALUES ('82', '6', 'چرداول');
INSERT INTO `county` VALUES ('83', '6', 'دره شهر');
INSERT INTO `county` VALUES ('84', '6', 'دهلران');
INSERT INTO `county` VALUES ('85', '6', 'سیروان');
INSERT INTO `county` VALUES ('86', '6', 'ملکشاهی');
INSERT INTO `county` VALUES ('87', '6', 'مهران');
INSERT INTO `county` VALUES ('88', '7', 'بوشهر');
INSERT INTO `county` VALUES ('89', '7', 'تنگستان');
INSERT INTO `county` VALUES ('90', '7', 'جم');
INSERT INTO `county` VALUES ('91', '7', 'دشتستان');
INSERT INTO `county` VALUES ('92', '7', 'دشتی');
INSERT INTO `county` VALUES ('93', '7', 'دیر');
INSERT INTO `county` VALUES ('94', '7', 'دیلم');
INSERT INTO `county` VALUES ('95', '7', 'عسلویه');
INSERT INTO `county` VALUES ('96', '7', 'کنگان');
INSERT INTO `county` VALUES ('97', '7', 'گناوه');
INSERT INTO `county` VALUES ('98', '8', 'اسلامشهر');
INSERT INTO `county` VALUES ('99', '8', 'بهارستان');
INSERT INTO `county` VALUES ('100', '8', 'پاکدشت');
INSERT INTO `county` VALUES ('101', '8', 'پردیس');
INSERT INTO `county` VALUES ('102', '8', 'پیشوا');
INSERT INTO `county` VALUES ('103', '8', 'تهران');
INSERT INTO `county` VALUES ('104', '8', 'دماوند');
INSERT INTO `county` VALUES ('105', '8', 'رباطکریم');
INSERT INTO `county` VALUES ('106', '8', 'ری');
INSERT INTO `county` VALUES ('107', '8', 'شمیرانات');
INSERT INTO `county` VALUES ('108', '8', 'شهریار');
INSERT INTO `county` VALUES ('109', '8', 'فیروزکوه');
INSERT INTO `county` VALUES ('110', '8', 'قدس');
INSERT INTO `county` VALUES ('111', '8', 'قرچک');
INSERT INTO `county` VALUES ('112', '8', 'ملارد');
INSERT INTO `county` VALUES ('113', '8', 'ورامین');
INSERT INTO `county` VALUES ('114', '9', 'اردل');
INSERT INTO `county` VALUES ('115', '9', 'بروجن');
INSERT INTO `county` VALUES ('116', '9', 'بن');
INSERT INTO `county` VALUES ('117', '9', 'سامان');
INSERT INTO `county` VALUES ('118', '9', 'شهرکرد');
INSERT INTO `county` VALUES ('119', '9', 'فارسان');
INSERT INTO `county` VALUES ('120', '9', 'کوهرنگ');
INSERT INTO `county` VALUES ('121', '9', 'کیار');
INSERT INTO `county` VALUES ('122', '9', 'لردگان');
INSERT INTO `county` VALUES ('123', '10', 'بشرویه');
INSERT INTO `county` VALUES ('124', '10', 'بیرجند');
INSERT INTO `county` VALUES ('125', '10', 'خوسف');
INSERT INTO `county` VALUES ('126', '10', 'درمیان');
INSERT INTO `county` VALUES ('127', '10', 'زیرکوه');
INSERT INTO `county` VALUES ('128', '10', 'سرایان');
INSERT INTO `county` VALUES ('129', '10', 'سربیشه');
INSERT INTO `county` VALUES ('130', '10', 'طبس');
INSERT INTO `county` VALUES ('131', '10', 'فردوس');
INSERT INTO `county` VALUES ('132', '10', 'قاینات');
INSERT INTO `county` VALUES ('133', '10', 'نهبندان');
INSERT INTO `county` VALUES ('134', '11', 'باخرز');
INSERT INTO `county` VALUES ('135', '11', 'بجستان');
INSERT INTO `county` VALUES ('136', '11', 'بردسکن');
INSERT INTO `county` VALUES ('137', '11', 'بینالود');
INSERT INTO `county` VALUES ('138', '11', 'تایباد');
INSERT INTO `county` VALUES ('139', '11', 'تربت جام');
INSERT INTO `county` VALUES ('140', '11', 'تربت حیدریه');
INSERT INTO `county` VALUES ('141', '11', 'جغتای');
INSERT INTO `county` VALUES ('142', '11', 'جوین');
INSERT INTO `county` VALUES ('143', '11', 'چناران');
INSERT INTO `county` VALUES ('144', '11', 'خلیل آباد');
INSERT INTO `county` VALUES ('145', '11', 'خواف');
INSERT INTO `county` VALUES ('146', '11', 'خوشاب');
INSERT INTO `county` VALUES ('147', '11', 'داورزن');
INSERT INTO `county` VALUES ('148', '11', 'درگز');
INSERT INTO `county` VALUES ('149', '11', 'رشتخوار');
INSERT INTO `county` VALUES ('150', '11', 'زاوه');
INSERT INTO `county` VALUES ('151', '11', 'سبزوار');
INSERT INTO `county` VALUES ('152', '11', 'سرخس');
INSERT INTO `county` VALUES ('153', '11', 'فریمان');
INSERT INTO `county` VALUES ('154', '11', 'فیروزه');
INSERT INTO `county` VALUES ('155', '11', 'قوچان');
INSERT INTO `county` VALUES ('156', '11', 'کاشمر');
INSERT INTO `county` VALUES ('157', '11', 'کلات');
INSERT INTO `county` VALUES ('158', '11', 'گناباد');
INSERT INTO `county` VALUES ('159', '11', 'مشهد');
INSERT INTO `county` VALUES ('160', '11', 'مه ولات');
INSERT INTO `county` VALUES ('161', '11', 'نیشابور');
INSERT INTO `county` VALUES ('162', '12', 'اسفراین');
INSERT INTO `county` VALUES ('163', '12', 'بجنورد');
INSERT INTO `county` VALUES ('164', '12', 'جاجرم');
INSERT INTO `county` VALUES ('165', '12', 'راز و جرگلان');
INSERT INTO `county` VALUES ('166', '12', 'شیروان');
INSERT INTO `county` VALUES ('167', '12', 'فاروج');
INSERT INTO `county` VALUES ('168', '12', 'گرمه');
INSERT INTO `county` VALUES ('169', '12', 'مانه وسملقان');
INSERT INTO `county` VALUES ('170', '13', 'آبادان');
INSERT INTO `county` VALUES ('171', '13', 'آغاجاری');
INSERT INTO `county` VALUES ('172', '13', 'امیدیه');
INSERT INTO `county` VALUES ('173', '13', 'اندیکا');
INSERT INTO `county` VALUES ('174', '13', 'اندیمشک');
INSERT INTO `county` VALUES ('175', '13', 'اهواز');
INSERT INTO `county` VALUES ('176', '13', 'ایذه');
INSERT INTO `county` VALUES ('177', '13', 'باغ ملک');
INSERT INTO `county` VALUES ('178', '13', 'باوی');
INSERT INTO `county` VALUES ('179', '13', 'بندرماهشهر');
INSERT INTO `county` VALUES ('180', '13', 'بهبهان');
INSERT INTO `county` VALUES ('181', '13', 'حمیدیه');
INSERT INTO `county` VALUES ('182', '13', 'خرمشهر');
INSERT INTO `county` VALUES ('183', '13', 'دزفول');
INSERT INTO `county` VALUES ('184', '13', 'دشت آزادگان');
INSERT INTO `county` VALUES ('185', '13', 'رامشیر');
INSERT INTO `county` VALUES ('186', '13', 'رامهرمز');
INSERT INTO `county` VALUES ('187', '13', 'شادگان');
INSERT INTO `county` VALUES ('188', '13', 'شوش');
INSERT INTO `county` VALUES ('189', '13', 'شوشتر');
INSERT INTO `county` VALUES ('190', '13', 'کارون');
INSERT INTO `county` VALUES ('191', '13', 'گتوند');
INSERT INTO `county` VALUES ('192', '13', 'لالی');
INSERT INTO `county` VALUES ('193', '13', 'مسجدسلیمان');
INSERT INTO `county` VALUES ('194', '13', 'هفتگل');
INSERT INTO `county` VALUES ('195', '13', 'هندیجان');
INSERT INTO `county` VALUES ('196', '13', 'هویزه');
INSERT INTO `county` VALUES ('197', '14', 'ابهر');
INSERT INTO `county` VALUES ('198', '14', 'ایجرود');
INSERT INTO `county` VALUES ('199', '14', 'خدابنده');
INSERT INTO `county` VALUES ('200', '14', 'خرمدره');
INSERT INTO `county` VALUES ('201', '14', 'زنجان');
INSERT INTO `county` VALUES ('202', '14', 'سلطانیه');
INSERT INTO `county` VALUES ('203', '14', 'طارم');
INSERT INTO `county` VALUES ('204', '14', 'ماهنشان');
INSERT INTO `county` VALUES ('205', '15', 'آرادان');
INSERT INTO `county` VALUES ('206', '15', 'دامغان');
INSERT INTO `county` VALUES ('207', '15', 'سرخه');
INSERT INTO `county` VALUES ('208', '15', 'سمنان');
INSERT INTO `county` VALUES ('209', '15', 'شاهرود');
INSERT INTO `county` VALUES ('210', '15', 'گرمسار');
INSERT INTO `county` VALUES ('211', '15', 'مهدی شهر');
INSERT INTO `county` VALUES ('212', '15', 'میامی');
INSERT INTO `county` VALUES ('213', '16', 'ایرانشهر');
INSERT INTO `county` VALUES ('214', '16', 'چابهار');
INSERT INTO `county` VALUES ('215', '16', 'خاش');
INSERT INTO `county` VALUES ('216', '16', 'دلگان');
INSERT INTO `county` VALUES ('217', '16', 'زابل');
INSERT INTO `county` VALUES ('218', '16', 'زاهدان');
INSERT INTO `county` VALUES ('219', '16', 'زهک');
INSERT INTO `county` VALUES ('220', '16', 'سراوان');
INSERT INTO `county` VALUES ('221', '16', 'سرباز');
INSERT INTO `county` VALUES ('222', '16', 'سیب و سوران');
INSERT INTO `county` VALUES ('223', '16', 'فنوج');
INSERT INTO `county` VALUES ('224', '16', 'قصرقند');
INSERT INTO `county` VALUES ('225', '16', 'کنارک');
INSERT INTO `county` VALUES ('226', '16', 'مهرستان');
INSERT INTO `county` VALUES ('227', '16', 'میرجاوه');
INSERT INTO `county` VALUES ('228', '16', 'نیک شهر');
INSERT INTO `county` VALUES ('229', '16', 'نیمروز');
INSERT INTO `county` VALUES ('230', '16', 'هامون');
INSERT INTO `county` VALUES ('231', '16', 'هیرمند');
INSERT INTO `county` VALUES ('232', '17', 'آباده');
INSERT INTO `county` VALUES ('233', '17', 'ارسنجان');
INSERT INTO `county` VALUES ('234', '17', 'استهبان');
INSERT INTO `county` VALUES ('235', '17', 'اقلید');
INSERT INTO `county` VALUES ('236', '17', 'بوانات');
INSERT INTO `county` VALUES ('237', '17', 'پاسارگاد');
INSERT INTO `county` VALUES ('238', '17', 'جهرم');
INSERT INTO `county` VALUES ('239', '17', 'خرامه');
INSERT INTO `county` VALUES ('240', '17', 'خرم بید');
INSERT INTO `county` VALUES ('241', '17', 'خنج');
INSERT INTO `county` VALUES ('242', '17', 'داراب');
INSERT INTO `county` VALUES ('243', '17', 'رستم');
INSERT INTO `county` VALUES ('244', '17', 'زرین دشت');
INSERT INTO `county` VALUES ('245', '17', 'سپیدان');
INSERT INTO `county` VALUES ('246', '17', 'سروستان');
INSERT INTO `county` VALUES ('247', '17', 'شیراز');
INSERT INTO `county` VALUES ('248', '17', 'فراشبند');
INSERT INTO `county` VALUES ('249', '17', 'فسا');
INSERT INTO `county` VALUES ('250', '17', 'فیروزآباد');
INSERT INTO `county` VALUES ('251', '17', 'قیروکارزین');
INSERT INTO `county` VALUES ('252', '17', 'کازرون');
INSERT INTO `county` VALUES ('253', '17', 'کوار');
INSERT INTO `county` VALUES ('254', '17', 'گراش');
INSERT INTO `county` VALUES ('255', '17', 'لارستان');
INSERT INTO `county` VALUES ('256', '17', 'لامرد');
INSERT INTO `county` VALUES ('257', '17', 'مرودشت');
INSERT INTO `county` VALUES ('258', '17', 'ممسنی');
INSERT INTO `county` VALUES ('259', '17', 'مهر');
INSERT INTO `county` VALUES ('260', '17', 'نی ریز');
INSERT INTO `county` VALUES ('261', '18', 'آبیک');
INSERT INTO `county` VALUES ('262', '18', 'آوج');
INSERT INTO `county` VALUES ('263', '18', 'البرز');
INSERT INTO `county` VALUES ('264', '18', 'بویین زهرا');
INSERT INTO `county` VALUES ('265', '18', 'تاکستان');
INSERT INTO `county` VALUES ('266', '18', 'قزوین');
INSERT INTO `county` VALUES ('267', '19', 'قم');
INSERT INTO `county` VALUES ('268', '20', 'بانه');
INSERT INTO `county` VALUES ('269', '20', 'بیجار');
INSERT INTO `county` VALUES ('270', '20', 'دهگلان');
INSERT INTO `county` VALUES ('271', '20', 'دیواندره');
INSERT INTO `county` VALUES ('272', '20', 'سروآباد');
INSERT INTO `county` VALUES ('273', '20', 'سقز');
INSERT INTO `county` VALUES ('274', '20', 'سنندج');
INSERT INTO `county` VALUES ('275', '20', 'قروه');
INSERT INTO `county` VALUES ('276', '20', 'کامیاران');
INSERT INTO `county` VALUES ('277', '20', 'مریوان');
INSERT INTO `county` VALUES ('278', '21', 'ارزوییه');
INSERT INTO `county` VALUES ('279', '21', 'انار');
INSERT INTO `county` VALUES ('280', '21', 'بافت');
INSERT INTO `county` VALUES ('281', '21', 'بردسیر');
INSERT INTO `county` VALUES ('282', '21', 'بم');
INSERT INTO `county` VALUES ('283', '21', 'جیرفت');
INSERT INTO `county` VALUES ('284', '21', 'رابر');
INSERT INTO `county` VALUES ('285', '21', 'راور');
INSERT INTO `county` VALUES ('286', '21', 'رفسنجان');
INSERT INTO `county` VALUES ('287', '21', 'رودبارجنوب');
INSERT INTO `county` VALUES ('288', '21', 'ریگان');
INSERT INTO `county` VALUES ('289', '21', 'زرند');
INSERT INTO `county` VALUES ('290', '21', 'سیرجان');
INSERT INTO `county` VALUES ('291', '21', 'شهربابک');
INSERT INTO `county` VALUES ('292', '21', 'عنبرآباد');
INSERT INTO `county` VALUES ('293', '21', 'فاریاب');
INSERT INTO `county` VALUES ('294', '21', 'فهرج');
INSERT INTO `county` VALUES ('295', '21', 'قلعه گنج');
INSERT INTO `county` VALUES ('296', '21', 'کرمان');
INSERT INTO `county` VALUES ('297', '21', 'کوهبنان');
INSERT INTO `county` VALUES ('298', '21', 'کهنوج');
INSERT INTO `county` VALUES ('299', '21', 'منوجان');
INSERT INTO `county` VALUES ('300', '21', 'نرماشیر');
INSERT INTO `county` VALUES ('301', '22', 'اسلام آبادغرب');
INSERT INTO `county` VALUES ('302', '22', 'پاوه');
INSERT INTO `county` VALUES ('303', '22', 'ثلاث باباجانی');
INSERT INTO `county` VALUES ('304', '22', 'جوانرود');
INSERT INTO `county` VALUES ('305', '22', 'دالاهو');
INSERT INTO `county` VALUES ('306', '22', 'روانسر');
INSERT INTO `county` VALUES ('307', '22', 'سرپل ذهاب');
INSERT INTO `county` VALUES ('308', '22', 'سنقر');
INSERT INTO `county` VALUES ('309', '22', 'صحنه');
INSERT INTO `county` VALUES ('310', '22', 'قصرشیرین');
INSERT INTO `county` VALUES ('311', '22', 'کرمانشاه');
INSERT INTO `county` VALUES ('312', '22', 'کنگاور');
INSERT INTO `county` VALUES ('313', '22', 'گیلانغرب');
INSERT INTO `county` VALUES ('314', '22', 'هرسین');
INSERT INTO `county` VALUES ('315', '23', 'باشت');
INSERT INTO `county` VALUES ('316', '23', 'بویراحمد');
INSERT INTO `county` VALUES ('317', '23', 'بهمیی');
INSERT INTO `county` VALUES ('318', '23', 'چرام');
INSERT INTO `county` VALUES ('319', '23', 'دنا');
INSERT INTO `county` VALUES ('320', '23', 'کهگیلویه');
INSERT INTO `county` VALUES ('321', '23', 'گچساران');
INSERT INTO `county` VALUES ('322', '23', 'لنده');
INSERT INTO `county` VALUES ('323', '24', 'آزادشهر');
INSERT INTO `county` VALUES ('324', '24', 'آق قلا');
INSERT INTO `county` VALUES ('325', '24', 'بندرگز');
INSERT INTO `county` VALUES ('326', '24', 'ترکمن');
INSERT INTO `county` VALUES ('327', '24', 'رامیان');
INSERT INTO `county` VALUES ('328', '24', 'علی آباد');
INSERT INTO `county` VALUES ('329', '24', 'کردکوی');
INSERT INTO `county` VALUES ('330', '24', 'کلاله');
INSERT INTO `county` VALUES ('331', '24', 'گالیکش');
INSERT INTO `county` VALUES ('332', '24', 'گرگان');
INSERT INTO `county` VALUES ('333', '24', 'گمیشان');
INSERT INTO `county` VALUES ('334', '24', 'گنبدکاووس');
INSERT INTO `county` VALUES ('335', '24', 'مراوه تپه');
INSERT INTO `county` VALUES ('336', '24', 'مینودشت');
INSERT INTO `county` VALUES ('337', '25', 'آستارا');
INSERT INTO `county` VALUES ('338', '25', 'آستانه اشرفیه');
INSERT INTO `county` VALUES ('339', '25', 'املش');
INSERT INTO `county` VALUES ('340', '25', 'بندرانزلی');
INSERT INTO `county` VALUES ('341', '25', 'رشت');
INSERT INTO `county` VALUES ('342', '25', 'رضوانشهر');
INSERT INTO `county` VALUES ('343', '25', 'رودبار');
INSERT INTO `county` VALUES ('344', '25', 'رودسر');
INSERT INTO `county` VALUES ('345', '25', 'سیاهکل');
INSERT INTO `county` VALUES ('346', '25', 'شفت');
INSERT INTO `county` VALUES ('347', '25', 'صومعه سرا');
INSERT INTO `county` VALUES ('348', '25', 'طوالش');
INSERT INTO `county` VALUES ('349', '25', 'فومن');
INSERT INTO `county` VALUES ('350', '25', 'لاهیجان');
INSERT INTO `county` VALUES ('351', '25', 'لنگرود');
INSERT INTO `county` VALUES ('352', '25', 'ماسال');
INSERT INTO `county` VALUES ('353', '26', 'ازنا');
INSERT INTO `county` VALUES ('354', '26', 'الیگودرز');
INSERT INTO `county` VALUES ('355', '26', 'بروجرد');
INSERT INTO `county` VALUES ('356', '26', 'پلدختر');
INSERT INTO `county` VALUES ('357', '26', 'خرم آباد');
INSERT INTO `county` VALUES ('358', '26', 'دلفان');
INSERT INTO `county` VALUES ('359', '26', 'دورود');
INSERT INTO `county` VALUES ('360', '26', 'دوره');
INSERT INTO `county` VALUES ('361', '26', 'رومشکان');
INSERT INTO `county` VALUES ('362', '26', 'سلسله');
INSERT INTO `county` VALUES ('363', '26', 'کوهدشت');
INSERT INTO `county` VALUES ('364', '27', 'آمل');
INSERT INTO `county` VALUES ('365', '27', 'بابل');
INSERT INTO `county` VALUES ('366', '27', 'بابلسر');
INSERT INTO `county` VALUES ('367', '27', 'بهشهر');
INSERT INTO `county` VALUES ('368', '27', 'تنکابن');
INSERT INTO `county` VALUES ('369', '27', 'جویبار');
INSERT INTO `county` VALUES ('370', '27', 'چالوس');
INSERT INTO `county` VALUES ('371', '27', 'رامسر');
INSERT INTO `county` VALUES ('372', '27', 'ساری');
INSERT INTO `county` VALUES ('373', '27', 'سوادکوه');
INSERT INTO `county` VALUES ('374', '27', 'سوادکوه شمالی');
INSERT INTO `county` VALUES ('375', '27', 'سیمرغ');
INSERT INTO `county` VALUES ('376', '27', 'عباس آباد');
INSERT INTO `county` VALUES ('377', '27', 'فریدونکنار');
INSERT INTO `county` VALUES ('378', '27', 'قایم شهر');
INSERT INTO `county` VALUES ('379', '27', 'کلاردشت');
INSERT INTO `county` VALUES ('380', '27', 'گلوگاه');
INSERT INTO `county` VALUES ('381', '27', 'محمودآباد');
INSERT INTO `county` VALUES ('382', '27', 'میاندورود');
INSERT INTO `county` VALUES ('383', '27', 'نکا');
INSERT INTO `county` VALUES ('384', '27', 'نور');
INSERT INTO `county` VALUES ('385', '27', 'نوشهر');
INSERT INTO `county` VALUES ('386', '28', 'آشتیان');
INSERT INTO `county` VALUES ('387', '28', 'اراک');
INSERT INTO `county` VALUES ('388', '28', 'تفرش');
INSERT INTO `county` VALUES ('389', '28', 'خمین');
INSERT INTO `county` VALUES ('390', '28', 'خنداب');
INSERT INTO `county` VALUES ('391', '28', 'دلیجان');
INSERT INTO `county` VALUES ('392', '28', 'زرندیه');
INSERT INTO `county` VALUES ('393', '28', 'ساوه');
INSERT INTO `county` VALUES ('394', '28', 'شازند');
INSERT INTO `county` VALUES ('395', '28', 'فراهان');
INSERT INTO `county` VALUES ('396', '28', 'کمیجان');
INSERT INTO `county` VALUES ('397', '28', 'محلات');
INSERT INTO `county` VALUES ('398', '29', 'ابوموسی');
INSERT INTO `county` VALUES ('399', '29', 'بستک');
INSERT INTO `county` VALUES ('400', '29', 'بشاگرد');
INSERT INTO `county` VALUES ('401', '29', 'بندرعباس');
INSERT INTO `county` VALUES ('402', '29', 'بندرلنگه');
INSERT INTO `county` VALUES ('403', '29', 'پارسیان');
INSERT INTO `county` VALUES ('404', '29', 'جاسک');
INSERT INTO `county` VALUES ('405', '29', 'حاجی اباد');
INSERT INTO `county` VALUES ('406', '29', 'خمیر');
INSERT INTO `county` VALUES ('407', '29', 'رودان');
INSERT INTO `county` VALUES ('408', '29', 'سیریک');
INSERT INTO `county` VALUES ('409', '29', 'قشم');
INSERT INTO `county` VALUES ('410', '29', 'میناب');
INSERT INTO `county` VALUES ('411', '30', 'اسدآباد');
INSERT INTO `county` VALUES ('412', '30', 'بهار');
INSERT INTO `county` VALUES ('413', '30', 'تویسرکان');
INSERT INTO `county` VALUES ('414', '30', 'رزن');
INSERT INTO `county` VALUES ('415', '30', 'فامنین');
INSERT INTO `county` VALUES ('416', '30', 'کبودرآهنگ');
INSERT INTO `county` VALUES ('417', '30', 'ملایر');
INSERT INTO `county` VALUES ('418', '30', 'نهاوند');
INSERT INTO `county` VALUES ('419', '30', 'همدان');
INSERT INTO `county` VALUES ('420', '31', 'ابرکوه');
INSERT INTO `county` VALUES ('421', '31', 'اردکان');
INSERT INTO `county` VALUES ('422', '31', 'اشکذر');
INSERT INTO `county` VALUES ('423', '31', 'بافق');
INSERT INTO `county` VALUES ('424', '31', 'بهاباد');
INSERT INTO `county` VALUES ('425', '31', 'تفت');
INSERT INTO `county` VALUES ('426', '31', 'خاتم');
INSERT INTO `county` VALUES ('427', '31', 'مهریز');
INSERT INTO `county` VALUES ('428', '31', 'میبد');
INSERT INTO `county` VALUES ('429', '31', 'یزد');
